version: "3.9"

services:
    laravelapp:
        container_name: laravelapp
        image: jay75chauhan/laravel-crud-docker:1.0.1
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - laraveldb

    laraveldb:
        container_name: laraveldb
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - laraveldb:/var/lib/postgresql/data

volumes:
    laraveldb: {}
